
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Santiago
 */
public class Combobox extends javax.swing.JFrame {

    /**
     * Creates new form Combobox
     */
    public Combobox() {
        initComponents();
        this.setTitle("Agregar elementos Combobox");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldModulo = new javax.swing.JTextField();
        comboBoxModulos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAnadir = new javax.swing.JButton();
        btnAgregarTodo = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        comboBoxCurso = new javax.swing.JComboBox<>();
        BotonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFieldModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldModuloActionPerformed(evt);
            }
        });

        comboBoxModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModulosActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Añade los modulos a los que estes matriculado:");
        jScrollPane1.setViewportView(jTextArea1);

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnAgregarTodo.setText("Añadir Todo");
        btnAgregarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTodoActionPerformed(evt);
            }
        });

        btnBorrarTodo.setText("Borrar Todo");
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });

        comboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo" }));
        comboBoxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCursoActionPerformed(evt);
            }
        });

        BotonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnadir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarTodo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBorrarTodo, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(comboBoxModulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFieldModulo)
                    .addComponent(BotonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxModulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadir)
                    .addComponent(btnAgregarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrarTodo)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldModuloActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        String curso = comboBoxCurso.getSelectedItem().toString();
        String prefijo = curso.equals("Primero") ? "1º " : "2º ";

        // Obtener el texto ingresado en el campo de texto
        String newItem = txtFieldModulo.getText().trim();

        // Verificar si el campo de texto está vacío
        if (newItem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Agregar el prefijo al nuevo ítem
        newItem = prefijo + newItem;

        // Verificar si el elemento ya está en el combobox
        boolean exists = false;
        for (int i = 0; i < comboBoxModulos.getItemCount(); i++) {
            if (comboBoxModulos.getItemAt(i).equals(newItem)) {
                exists = true;
                break;
            }
        }

        if (exists) {
            JOptionPane.showMessageDialog(this, "Este elemento ya existe en la lista", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            comboBoxModulos.addItem(newItem);  // Añadir el nuevo elemento al combobox con el prefijo
            txtFieldModulo.setText("");  // Limpiar el campo de texto
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void comboBoxModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxModulosActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        // TODO add your handling code here:
        comboBoxModulos.removeAllItems();
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btnAgregarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTodoActionPerformed
        // TODO add your handling code here:

        String curso = comboBoxCurso.getSelectedItem().toString();
        String prefijo = curso.equals("Primero") ? "1" : "2";
      

        String[] modulosPrimero = {"Programacion", "Base de datos", "Lenguaje de marcas"};
        String[] modulosSegundo = {"Programación multimedia", "Acceso a datos", "Desarrollo de Interfaces"};

        String[] modulosCurso = curso.equals("Primero") ? modulosPrimero : modulosSegundo;

        for (String modulo : modulosCurso) {
            boolean exists = false;
            for (int i = 0; i < comboBoxModulos.getItemCount(); i++) {
                if (comboBoxModulos.getItemAt(i).equals(curso + "º " + modulo)) {
                    exists = true;
                    break;
                }
            }
            if (!exists) {
                comboBoxModulos.addItem(prefijo + "º " + modulo);
            }
        }
    }//GEN-LAST:event_btnAgregarTodoActionPerformed

    private void comboBoxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCursoActionPerformed
        // TODO add your handling code here:

        String curso = comboBoxCurso.getSelectedItem().toString();
        String modulo = txtFieldModulo.getText();
        String prefijo = curso.equals("Primero") ? "1" : "2";

        boolean exists = false;
        for (int i = 0; i < comboBoxModulos.getItemCount(); i++) {
            if (comboBoxModulos.getItemAt(i).equals(prefijo + "º " + modulo)) {
                exists = true;
                break;
            }
        }

        if (!exists && !modulo.isEmpty()) {
            comboBoxModulos.addItem(prefijo + "º " + modulo);
        }


    }//GEN-LAST:event_comboBoxCursoActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:

        int selectedIndex = comboBoxModulos.getSelectedIndex();
        if (selectedIndex != -1) {
            comboBoxModulos.removeItemAt(selectedIndex);
        }
    }//GEN-LAST:event_BotonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            // Cambiar el Look and Feel al estilo de Windows
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton btnAgregarTodo;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JComboBox<String> comboBoxCurso;
    private javax.swing.JComboBox<String> comboBoxModulos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtFieldModulo;
    // End of variables declaration//GEN-END:variables
}
